// Generated by https://quicktype.io

export interface CodePipelineExecutionStateChange {
    account:              string;
    detailType:           string;
    region:               string;
    source:               string;
    time:                 string;
    notificationRuleArn:  string;
    detail:               Detail;
    resources:            string[];
    additionalAttributes: JSON;
}

export interface AdditionalAttributes {
}

export interface Detail {
    pipeline:            string;
    "execution-id":      string;
    "execution-trigger": ExecutionTrigger;
    state:               string;
    version:             number;
}

export interface ExecutionTrigger {
    "trigger-type":   string;
    "trigger-detail": string;
}
