// Generated by https://quicktype.io

export interface SNSEvent {
    Records: Record[];
}

export interface Record {
    EventSource:          string;
    EventVersion:         string;
    EventSubscriptionArn: string;
    Sns:                  SnsMessage;
}

export interface SnsMessage {
    Type:              string;
    MessageId:         string;
    TopicArn:          string;
    Subject:           string|null;
    Message:           string;
    Timestamp:         string;
    SignatureVersion:  string;
    Signature:         string;
    SigningCertUrl:    string;
    UnsubscribeUrl:    string;
    MessageAttributes: JSON;
}

